development:
  access_key_id: "AKIAIEMNN7BAULT3LJZQ"
  secret_access_key: "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"
  bucket: "mylavailbucket"
  s3_region: "us-west-2"


production:
  access_key_id: "AKIAIEMNN7BAULT3LJZQ"
  secret_access_key: "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"
  bucket: "mylavailbucket"
  s3_region: "us-west-2"
